In [2]:
import torch
import torch.nn as nn

In [3]:
class CurveModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(7, 128)
        self.relu = nn.LeakyReLU()
        self.fc2 = nn.Linear(128, 128)
        self.fc3 = nn.Linear(128, 3)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

In [4]:
device = torch.device('cuda')

In [5]:
model = CurveModel()

In [6]:
model.load_state_dict(torch.load('../models/straight_model.pth'))

<All keys matched successfully>

In [9]:
a = torch.tensor([[-3.5612,  0.2578,  0., 0.0969, 0.6768, 0., 0.]])

In [10]:
model(a)

tensor([[-3.2817,  0.8750, -0.1744]], grad_fn=<AddmmBackward>)

In [9]:
-3.3308+0.8029*2.0015

-1.72379565

tensor([-1.7239, -0.4986,  0.9527])

In [12]:
a.data

tensor([[-3.3308, -0.9779,  2.0492,  0.8029,  0.2395, -0.5479,  2.0015]])

In [13]:
0.8029**2 + 0.2395**2 + 0.5479**2

1.00220307